server:
  port: 5000

app:
  datasource:
    jdbc-url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    pool-size: 200

application:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14

logging:
  level:
    com:
      leaguebackend: DEBUG
  file:
    name: logfile.log

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
